project:
  id: "shortbread"
  name: "OriLibre - Shortbread"
  description: "Using OpenStreetMap Shortbread"
map:
  center: [0, 0]
  zoom: 1
  bearing: 0
  pitch: 0
  glyphs: https://tiles.versatiles.org/assets/glyphs/{fontstack}/{range}.pbf
resources:
  design-plan:
    file: "https://cdn.jsdelivr.net/gh/tjmsy/isomizer-projectfiles@0.6/projects/shortbread/design-plan.yml"
  symbol-palette:
    file: "https://cdn.jsdelivr.net/gh/tjmsy/isomizer-projectfiles@0.6/palettes/isom2017/symbol-palette.yml"
  color-palette:
    file: "https://cdn.jsdelivr.net/gh/tjmsy/isomizer-projectfiles@0.6/palettes/isom2017/color-palette.yml"
  image-palette:
    file: "https://cdn.jsdelivr.net/gh/tjmsy/isomizer-projectfiles@0.6/palettes/isom2017/image-palette.yml"
