project:
  name: "OpenFreeMap to ISOM2017-2"
  description: "OpenFreeMap to ISOM2017-2"

map:
  center: [0,0]
  zoom: 1
  bearing: 0
  pitch: 0

resources:
  design-plan:
    file: "https://cdn.jsdelivr.net/gh/tjmsy/isomizer-projectfiles/ofm-isom/design-plan.yml"
  symbol-palette:
    file: "https://cdn.jsdelivr.net/gh/tjmsy/isomizer-projectfiles/ofm-isom//palettes/symbol-palette.yml"
  color-palette:
    file: "https://cdn.jsdelivr.net/gh/tjmsy/isomizer-projectfiles/ofm-isom//palettes/color-palette.yml"
  svg-palette:
    file: "https://cdn.jsdelivr.net/gh/tjmsy/isomizer-projectfiles/ofm-isom//palettes/svg-palette.yml"
